### ISSUE TITLE
Network address of flink master should be configurable for each flink worker

### ISSUE THREAD

**Issue by earthquakesan** [big-data-europe/docker-flink#4]
At the moment the config is hardcoded as follows:

```
flinkmaster:
    image: bde2020/flink-master:0.10.1-hadoop2.7
    hostname: flink-master
    environment:
      - INIT_DAEMON_STEP=setup_flink
#    networks:
#      - flink
flinkworker:
    image: bde2020/flink-worker:0.10.1-hadoop2.7
    hostname: flink-worker
#    networks:
#     - flink
    links:
      - "flinkmaster:localhost"
```

The worker is connected to flinkmaster using hardcoded "localhost" host name (in master/slaves file?). The proper docker-compose.yml should look like:

```
flinkmaster:
    image: bde2020/flink-master:0.10.1-hadoop2.7
    environment:
      - INIT_DAEMON_STEP=setup_flink
flinkworker:
    image: bde2020/flink-worker:0.10.1-hadoop2.7
    links:
      - "flinkmaster"
    environment:
       - FLINK_MASTER=flinkmaster
```
